### ISSUE TITLE
[Crash]: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null

### ISSUE THREAD

**Issue by gatolover69** [clownless/Blockify#28]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/clownless/Blockify/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Blockify version.

1.2.4

### Fabric API version.

0.75.1

### What happened?

I don't know how to explain it, every once in a while, it will crash once it skips to the next song, not sure why since i'm not the most experienced in java, not experienced at all. Maybe its a mod conflict, but i genuinely don't have the patience to go through more than 20 mods :p
There is one that seems similar to mine, bug #9 

// **CRASH MESSAGE** \\

**info: [20:05:30] [Spotify Thread/ERROR]: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
info: [20:05:30] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[guava-31.0.1-jre.jar:?]
	at one.clownless.blockify.BlockifyHUD.draw(BlockifyHUD.java:117) ~[blockify-1.19.2-1.2.4.1.temp.jar:?]
	at net.minecraft.class_329.handler$zeb000$onDraw(class_329.java:4001) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:862) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.14.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) [rust-extension-1.0.7.jar:?]
info: [20:05:31] [Render thread/INFO]: Stopping worker threads
info: ---- Minecraft Crash Report ----
// My bad.

Time: 2023-03-09 20:05:31
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
	at one.clownless.blockify.BlockifyHUD.draw(BlockifyHUD.java:117)
	at net.minecraft.class_329.handler$zeb000$onDraw(class_329.java:4001)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
	at one.clownless.blockify.BlockifyHUD.draw(BlockifyHUD.java:117)
	at net.minecraft.class_329.handler$zeb000$onDraw(class_329.java:4001)
	at net.minecraft.class_329.method_1753(class_329.java)**

### Relevant logs

https://paste.gg/p/anonymous/6d39d2e391e64f0a869c9ee5dfb89aa5

**Comment by erruqietobedelete** [comment]
irrelevant
