### ISSUE TITLE
[Crash]: Crowdin translate mod infinitely loading game

### ISSUE THREAD

**Issue by mpschorr** [clownless/Blockify#29]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/clownless/Blockify/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.3

### Blockify version.

1.2.4.1

### Fabric API version.

0.76.0+1.19.3

### What happened?

Loading fabric 1.19.3 with Blockify causes the game to reload and spit a crowdin translate error in the console multiple times per second.

### Relevant logs

```
[17:57:17] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (AppleSkin, Blockify, Cloth Config v9, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Light Overlay, MidnightLib, Roughly Enough Items, Xaero's Minimap, Xaero's World Map)
[17:57:18] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method de/guntram/mcmod/crowdintranslate/CTResourcePack.method_14408(Lnet/minecraft/class_3264;Ljava/lang/String;Ljava/lang/String;Lnet/minecraft/class_3262$class_7664;)V is abstract
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.AbstractMethodError: Method de/guntram/mcmod/crowdintranslate/CTResourcePack.method_14408(Lnet/minecraft/class_3264;Ljava/lang/String;Ljava/lang/String;Lnet/minecraft/class_3262$class_7664;)V is abstract
	at de.guntram.mcmod.crowdintranslate.CTResourcePack.method_14408(CTResourcePack.java) ~[crowdin-translate-1.4+1.19-2862e7b423a76f9d.jar:?]
	at net.minecraft.class_3294.method_14488(class_3294.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.method_14488(class_6861.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_7654.method_45113(class_7654.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144$class_4009.method_45913(class_1144.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18180(class_1144.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18789(class_1144.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
```

### Additional information

I have these mods installed:
- Appleskin 2.4.2
- Architectury 7.1.70
- Light Overlay 7.0.2
- MRU 0.1.5
- RoughlyEnoughItems 10.0.596
- Xaero's Minimap 23.3.1
- Xaero's Worldmap 1.29.2

Visually, the game fades in and out between these very quickly
![image](https://user-images.githubusercontent.com/39606839/226751078-8c9292d7-d06b-4c6d-8ddf-19a372f064ff.png)
![image](https://user-images.githubusercontent.com/39606839/226751098-4184ff68-f7d3-4933-96ed-4fbea6436365.png)

**Comment by srnyx** [comment]
This is happening to me too on a fresh install with just Blockify (1.2.4.1) and Fabric API (0.76.0) using Fabric 0.14.19 on 1.19.3 (except I'm not getting any errors in console)

**Comment by erruqietobedelete** [comment]
irrelevant
